//! GitHub Actions workflow generation.
//!
//! Generates workflow YAML files for Cortex CI/CD automation.

use serde::{Deserialize, Serialize};

/// Workflow configuration options.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowConfig {
    /// Workflow name.
    pub name: String,
    /// Enable PR review automation.
    pub pr_review: bool,
    /// Enable issue automation.
    pub issue_automation: bool,
}

impl Default for WorkflowConfig {
    fn default() -> Self {
        Self {
            name: "Cortex".to_string(),
            pr_review: true,
            issue_automation: true,
        }
    }
}

/// Generate a workflow that analyzes trusted events without granting write tokens.
/// Results are private repository artifacts, not automatically posted comments.
pub fn generate_workflow(config: &WorkflowConfig) -> String {
    let name = serde_json::to_string(&config.name).expect("String serialization cannot fail");
    let mut triggers = String::new();
    if config.issue_automation {
        triggers.push_str(
            "  issue_comment:\n    types: [created]\n  issues:\n    types: [opened, labeled]\n",
        );
    }
    if config.pr_review {
        triggers.push_str("  pull_request:\n    types: [opened, synchronize, reopened]\n  pull_request_review:\n    types: [submitted]\n");
    }
    if triggers.is_empty() {
        return format!(
            "name: {name}\non:\n  workflow_dispatch:\npermissions: {{}}\njobs:\n  configuration:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo 'No Cortex automation event triggers are enabled.'\n"
        );
    }
    format!(
        r#"# Generated by Cortex github install. Review before enabling.
# Read-only analysis; no comments, branch writes, reviews, or reactions are posted.
# Configure the cortex-analysis environment with required reviewers if desired.
name: {name}
on:
{triggers}
permissions:
  contents: read
  issues: read
  pull-requests: read
concurrency:
  group: cortex-${{{{ github.repository }}}}-${{{{ github.event.issue.number || github.event.pull_request.number }}}}
  cancel-in-progress: false
jobs:
  cortex:
    runs-on: ubuntu-latest
    environment: cortex-analysis
    timeout-minutes: 10
    if: >-
      github.event.sender.type == 'User' &&
      (!github.event.pull_request || github.event.pull_request.head.repo.full_name == github.repository) &&
      ((github.event_name == 'pull_request' && !github.event.pull_request.draft &&
        contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.pull_request.author_association) &&
        github.event.sender.login == github.event.pull_request.user.login) ||
       (github.event_name == 'pull_request_review' &&
        contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.review.author_association) &&
        github.event.sender.login == github.event.review.user.login &&
        (contains(github.event.review.body, '@cortex') || contains(github.event.review.body, '/cortex'))) ||
       (github.event_name == 'issue_comment' &&
        contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association) &&
        github.event.sender.login == github.event.comment.user.login &&
        (contains(github.event.comment.body, '@cortex') || contains(github.event.comment.body, '/cortex'))) ||
       (github.event_name == 'issues' &&
        contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.issue.author_association) &&
        github.event.sender.login == github.event.issue.user.login))
    steps:
      - name: Checkout trusted default branch, never pull request code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{{{ github.event.repository.default_branch }}}}
          persist-credentials: false
      - name: Install Cortex CLI
        run: |
          curl -fsSL https://software.cortex.foundation/install.sh -o "$RUNNER_TEMP/install-cortex.sh"
          sh "$RUNNER_TEMP/install-cortex.sh"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Analyze event
        env:
          CORTEX_API_KEY: ${{{{ secrets.CORTEX_API_KEY }}}}
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          Cortex github run \
            --event "$GITHUB_EVENT_NAME" \
            --event-path "$GITHUB_EVENT_PATH" \
            --repository "$GITHUB_REPOSITORY" \
            --output "$RUNNER_TEMP/cortex-response.md"
      - name: Retain analysis for repository reviewers
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: cortex-analysis
          path: ${{{{ runner.temp }}}}/cortex-response.md
          if-no-files-found: ignore
          retention-days: 7
"#
    )
}

pub fn generate_pr_review_workflow(name: &str) -> String {
    generate_workflow(&WorkflowConfig {
        name: name.into(),
        pr_review: true,
        issue_automation: false,
    })
}

pub fn generate_issue_triage_workflow(name: &str) -> String {
    generate_workflow(&WorkflowConfig {
        name: name.into(),
        pr_review: false,
        issue_automation: true,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_workflow_default() {
        let config = WorkflowConfig::default();
        let workflow = generate_workflow(&config);

        assert!(workflow.contains("name: \"Cortex\""));
        assert!(workflow.contains("issue_comment:"));
        assert!(workflow.contains("pull_request:"));
        // Check for API key environment variable
        assert!(
            workflow.contains("API_KEY") || workflow.contains("CORTEX_API_KEY"),
            "Should contain API key env var"
        );
    }

    #[test]
    fn test_generate_workflow_pr_only() {
        let config = WorkflowConfig {
            name: "cortex-pr".to_string(),
            pr_review: true,
            issue_automation: false,
        };
        let workflow = generate_workflow(&config);

        assert!(workflow.contains("name: \"cortex-pr\""));
        assert!(workflow.contains("pull_request:"));
        assert!(!workflow.contains("issue_comment:"));
    }

    #[test]
    fn test_generate_pr_review_workflow() {
        let workflow = generate_pr_review_workflow("pr-review");

        assert!(workflow.contains("name: \"pr-review\""));
        assert!(workflow.contains("pull_request:"));
        assert!(workflow.contains("$HOME/.local/bin"));
        assert!(workflow.contains("software.cortex.foundation/install.sh"));
        assert!(!workflow.contains("issue_comment:"));
    }

    #[test]
    fn test_generate_issue_triage_workflow() {
        let workflow = generate_issue_triage_workflow("issue-triage");

        assert!(workflow.contains("name: \"issue-triage\""));
        assert!(workflow.contains("issues:"));
        assert!(workflow.contains("issue_comment:"));
    }
}
